### ISSUE TITLE
Deprecation warning with latest Puppet

### ISSUE THREAD

**Issue by jasondbaker** [saz/puppet-resolv_conf#38]
I see this deprecation warning running this module on Puppet 4.8.2: 

Warning: This method is deprecated, please use the stdlib validate_legacy function, with Stdlib::Compat::Array. There is further documentation for validate_legacy function in the README. at ["/tmp/vagrant-puppet/modules-d13e566bc1ef5c5b77f837a1b7abf98a/resolv_conf/manifests/init.pp", 24]:["/tmp/vagrant-puppet/modules-349b2fc5f7c6f9d1a4035056f56a248f/role/manifests/init.pp", 4

**Comment by bastelfreak** [comment]
@jasondbaker this will be fixed with https://github.com/saz/puppet-resolv_conf/pull/40

**Comment by saz** [comment]
This is fixed in the current master
