### ISSUE TITLE
Options should be one-per-line

### ISSUE THREAD

**Issue by gabe-sky** [saz/puppet-resolv_conf#42]
Currently the ERB template makes a single "options" like, with a concatentation of all of the elements in the options array.  This should actually be one options line per element in the array.

**Comment by saz** [comment]
Fixed in the current master

**Comment by ITBlogger** [comment]
Do you have any sort of documentation of resolv.conf to support this? asking because most examples out there have options all on one line. my team and I would love to know where the multi options line directive comes from
