### ISSUE TITLE
Issues with Debian 9 and Ubuntu 16.04 ?

### ISSUE THREAD

**Issue by jschaeff** [saz/puppet-resolv_conf#45]
Hi,

on these 2 systems I had to install the resolvconf package for this module to work. I didn't had to do this on other systems.

Does someone have the same issue ? Could this package be realized in the module ?

**Comment by hameno** [comment]
Yes, this is annoying as resolvconf breaks on reboot for statically configured network (atleast for us). Can we please switch that of?

**Comment by saz** [comment]
@hameno nothing inside resolv.conf after a reboot?

**Comment by hameno** [comment]
yes, exactly

**Comment by hameno** [comment]
From what I can see this module should probably edit "/etc/resolvconf/resolv.conf.d/base" instead of /etc/resolv.conf if resolvconf is installed.

**Comment by saz** [comment]
I think this module should handle package management of resolvconf package instead of changing its behavior if the package is installed. I think resolvconf is installed on Debian based distros by default nowadays.

**Comment by saz** [comment]
This is now configurable in the current master:
```
use_resolvconf => true, false (default: false)
manage_package => true, false (default: true on Debian based distros, false on all others)
package_ensure => present, absent,... (default: absent)
```
This should restore a static /etc/resolv.conf managed by puppet.

If possible, please give the current master a try @hameno @jschaeff

**Comment by saz** [comment]
I'll make a new release soon which will have a fix for this issue
