### ISSUE TITLE
Error while evaluating a Resource Statement upon release of v4.0.0

### ISSUE THREAD

**Issue by hiltonaipfw** [saz/puppet-resolv_conf#51]
Good afternoon! My Puppet server picked up the new release of the resolv_conf module today, and immediately started throwing the following error when it ran

`Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Resource Statement, Class[Resolv_conf]:
  expects a value for parameter 'config_file'
  expects a value for parameter 'config_template'
  expects a value for parameter 'use_resolvconf'
  expects a value for parameter 'update_cmd'
  expects a value for parameter 'package'
  expects a value for parameter 'manage_package'
  expects a value for parameter 'package_ensure' at /etc/puppetlabs/code/environments/production/site/profile/manifests/dns_config.pp:4:3 on node aarontest.ipfw.edu
`

My manifest is pretty simple and worked porperly before the update.

`class profile::dns_config {

  class { 'resolv_conf':
    nameservers => ['149.164.1.13'],
    domainname  => 'ipfw.edu',
  }
}`

Any suggestions? I'm on Puppet Enterprise 2016.4 (Puppet 4.7.0). Thanks!

**Comment by saz** [comment]
Hi! Sorry to hear that.


Which distro are you running (version, release,...)?

**Comment by mhudson1** [comment]
Those values are set in module data (see common linked below), something not working on your system with data in modules? Most of those params existed before this latest update as well.

https://github.com/saz/puppet-resolv_conf/blob/master/data/common.yaml

You may want to specify a tag/release of the module instead of just looking at master branch so you can test updates before they go live in your environment

**Comment by saz** [comment]
@hiltonaipfw Any news?

**Comment by hiltonaipfw** [comment]
I'm out of the office right now, so I can't guarantee the releases, but I know the problem exists on RHEL 6 and 7. I'll have more info for you tomorrow.



Sent from my Verizon, Samsung Galaxy smartphone


-------- Original message --------

**Comment by hiltonaipfw** [comment]
@saz - This is verified to be broken on RHEL 6.9, 7.3, 7.4, 7.5, and SLES 11.4. 

@mhudson1 - tagging the release has been on my radar for a while, but I've been lucky until now :)

**Comment by mhudson1** [comment]
I have tested on RHEL 6.9 and RHEL 7.5 (as well as AIX 7.1 and Solaris 10 and 11) myself without issues. We may need more info to help such as maybe a Puppet run with --debug specified.  FYI, I am the person that submitted PR #50, I am logged in with a different account than I submitted it with.

**Comment by mhudson1** [comment]
One other thing you may want to check, you should look on your master and ensure the module is downloaded with the same content as the source. Based on your original error output you should find the module at /etc/puppetlabs/code/environments/production/modules/resolv_conf and you should verify that module has a "data" folder and that the contents of data/common.yaml has the same data as the link I posted earlier. This will at least verify you have the default data the module should be looking for.

**Comment by saz** [comment]
@hiltonaipfw I'm also able to confirm that this is working as expected. As @mhudson1 suggested, can you please provide the output of a puppet run with --debug set?
