### ISSUE TITLE
 expects a value for parameter 'config_file'

### ISSUE THREAD

**Issue by Ragulb89** [saz/puppet-resolv_conf#54]
Hi,

i have simple class defined as below

class ent::dns (
  Array $searchpath,
  Array $ent_resolver,
) {
    class { 'resolv_conf':
      nameservers => $ent_resolver,
      searchpath  => $searchpath,
    }
  }

I could see the value config_file in fixture/modules/resolv_conf/data , but its not picking up the value. I am running this test on rhel7.5, all puppet facter works fine. any suggestions ?

**Comment by saz** [comment]
Can you give the current master a try?

**Comment by saz** [comment]
I'll close this issue, as there is no feedback.
