### ISSUE TITLE
Support custom comment header

### ISSUE THREAD

**Issue by bmcnally-uw** [saz/puppet-resolv_conf#60]
Rather than be forced to have this at the top of /etc/resolv.conf:

`# File managed by puppet`

It would be nice to support a custom string to be passed in instead. The existing behavior is a good default, but not everyone is going to want that header. Thanks for your consideration.

**Comment by saz** [comment]
A flag to disable it or a parameter to pass in a custom header?

**Comment by saz** [comment]
As there's no feedback and no other complaints, I'll close this issue.
