### ISSUE TITLE
Fix for Solaris 11

### ISSUE THREAD

**Issue by bonivart** [saz/puppet-resolv_conf#62]
Thanks for the Solaris 11 support but there's still two small issues. First is that Solaris wants the options space separated on one line, not one per line. If you have more than one option only the last one will count. Second is that Solaris writes back /etc/resolv.conf with the options line before the nameserver lines but the template does it the other way causing Puppet to "correct" it every time it runs.

The attached diff fixes both issues.

[resolv.sol11.diff.txt](https://github.com/saz/puppet-resolv_conf/files/3815957/resolv.sol11.diff.txt)

**Comment by saz** [comment]
Can you create a PR for that?

**Comment by bonivart** [comment]
I have done that now.

https://github.com/saz/puppet-resolv_conf/pull/63

**Comment by saz** [comment]
#63 is merged now. Can you test the current master?

**Comment by bonivart** [comment]
Thanks, I'm putting it into testing now. Will let you know next week.

**Comment by bonivart** [comment]
We're running it in production now, works fine on Solaris 11 and no regressions on other operating systems.
