### ISSUE TITLE
Request: allow puppetlabs-stdlib <8.0.0

### ISSUE THREAD

**Issue by rauschbit** [saz/puppet-resolv_conf#65]
# Use case
Please allow the module version <8.0.0 dependency for puppetlabs-stdlib because this module is already on version 7.1.0
https://github.com/puppetlabs/puppetlabs-stdlib 

Many thx in advance!

**Comment by saz** [comment]
[v5.0.0](https://github.com/saz/puppet-resolv_conf/tree/v5.0.0) has been released, fixing this issue

**Comment by rauschbit** [comment]
Wow, that was fast! Many thx!! 🙏
